# Generated by Django 4.1.2 on 2022-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=150, verbose_name='Post Text')),
                ('post_type', models.CharField(max_length=150, verbose_name='Post Type')),
            ],
        ),
    ]
